import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8000/');
  await page.getByText('Klik di mana saja untuk').click();
  await page.locator('input[name="nrp"]').click();
  await page.locator('input[name="nrp"]').fill('005100439');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('005100439');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Diklat', description: 'Diklat', exact: true }).click();
  await page.getByRole('button', { name: 'Tambah' }).click();
  await page.getByRole('textbox', { name: 'Tanggal Mulai Tanggal Selesai' }).fill('2025-05-22');
  await page.locator('#tanggal').nth(1).fill('2026-05-22');
  await page.getByRole('textbox', { name: 'Tanggal Mulai Tanggal Selesai' }).fill('2026-05-22');
  await page.getByRole('textbox', { name: 'Nama Diklat' }).click();
  await page.getByRole('textbox', { name: 'Nama Diklat' }).fill('Diklat Karyawan');
  await page.locator('select[name="diklat"]').selectOption('HLC');
  await page.getByRole('combobox', { name: 'Pengajar' }).click();
  await page.getByRole('textbox', { name: 'Penyelenggara' }).click();
  await page.getByRole('textbox', { name: 'Penyelenggara' }).fill('RSMDH');
  await page.getByRole('spinbutton', { name: 'Jam Diklat' }).click();
  await page.getByRole('spinbutton', { name: 'Jam Diklat' }).fill('1');
  await page.locator('#keterangan').nth(1).click();
  await page.locator('#keterangan').nth(1).fill('bagus');
  await page.locator('#keterangan').nth(2).click();
  await page.locator('#keterangan').nth(2).fill('bagus');
  await page.getByRole('button', { name: 'Upload Sertifikat' }).click();
  await page.getByRole('button', { name: 'Upload Sertifikat' }).setInputFiles('hasil_turnitin_1767684375748_Revisi.pdf');
  await page.goto('http://localhost:8000/Diklat/create');
  await page.getByRole('button', { name: 'Simpan Data' }).click();
});